[package]
name = "dsa"
version = "0.1.0"
edition = "2024"

[dependencies]
# CLI argument parsing
clap = { version = "4.0.32", features = ["derive"] }


# Error handling
anyhow = "1.0"

# Logging
log = "0.4"
env_logger = "0.9"

